name    'creativeview-mssql2012'
version '0.1.2'
source ''
author 'David Balharrie'
license 'Apache License 2.0'
summary 'Microsoft SQL Server 2012 Module for Puppet'
description 'Microsoft SQL Server 2012 Installation Module for Puppet'
project_page 'https://github.com/creativeview/puppet-mssql2012'

dependency 'puppetlabs/dism', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 3.1.0'
